package app

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"wechat/common"
	"wechat/global"
)

type AutoGeneratedEList struct {
	Ent struct {
		Items  []interface{} `json:"items"`
		More   bool          `json:"more"`
		Offset int           `json:"offset"`
	} `json:"ent"`
	Ext struct {
		Difficultyinfos []struct {
			Difficulty int    `json:"difficulty"`
			Name       string `json:"name"`
			Level      int    `json:"level"`
			Color      string `json:"color"`
			Status     int    `json:"status"`
			Count      int    `json:"count"`
			Bgimg      string `json:"bgimg"`
		} `json:"difficultyinfos"`
		Guidetext     string `json:"guidetext"`
		Isshowexplain bool   `json:"isshowexplain"`
		Levelinfo     struct {
			Level int    `json:"level"`
			Count int    `json:"count"`
			Name  string `json:"name"`
		} `json:"levelinfo"`
		Pkroute            string      `json:"pkroute"`
		Publishids         interface{} `json:"publishids"`
		Readids            interface{} `json:"readids"`
		Totalbookcn        int         `json:"totalbookcn"`
		Userdifficultyinfo struct {
			UID          int `json:"uid"`
			Difficulty   int `json:"difficulty"`
			Readcount    int `json:"readcount"`
			Publishcount int `json:"publishcount"`
		} `json:"userdifficultyinfo"`
	} `json:"ext"`
}

func listJson() AutoGeneratedEList {
	list := `{
            "ent": {
                "items": [
                    {
                        "avescore": 93,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 1,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/1.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/1.png",
                            "tiny": "https://oss.58haha.com/temp/1.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1589173525,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过小猫玩耍的故事，介绍字母组合at的发音。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 1,
                        "playcount": 2166890,
                        "pressid": 1004,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "自然拼读",
                            "字母组合",
                            "动物"
                        ],
                        "themeinfos": null,
                        "title": "Cat",
                        "top": 1589434362,
                        "topicbookindex": 0,
                        "topicid": 276975692752910,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1630583891,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 9,
                        "voicetype": 2,
                        "words": [
                            "cat",
                            "hat",
                            "mat"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 85,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 2,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/2.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 704,
                            "origin": "https://oss.58haha.com/temp/2.png",
                            "tiny": "https://oss.58haha.com/temp/2.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1527578476,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过展示不同自然现象，帮助学生了解常见天气。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 14687033,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "天气",
                            "自然"
                        ],
                        "themeinfos": null,
                        "title": "Weather",
                        "top": 1531973280,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419846,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 6,
                        "voicetype": 2,
                        "words": [
                            "snowy",
                            "cloudy",
                            "rainy"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 87,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 3,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/3.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/3.png",
                            "tiny": "https://oss.58haha.com/temp/3.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488454921,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过不同小朋友手的照片，学习与手相关的各个部位的表达。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 3182006,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "身体部位",
                            "手"
                        ],
                        "themeinfos": null,
                        "title": "Hands",
                        "top": 1509035052,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419847,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 9,
                        "voicetype": 2,
                        "words": [
                            "hands",
                            "fingers",
                            "nails"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 90,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 4,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/4.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 704,
                            "origin": "https://oss.58haha.com/temp/4.png",
                            "tiny": "https://oss.58haha.com/temp/4.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488457018,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过介绍常见的不同学习用品，帮助孩子了解常见学习用品的名称。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 2729942,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "学校",
                            "学习用品"
                        ],
                        "themeinfos": null,
                        "title": "School Tools",
                        "top": 364,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419846,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 10,
                        "voicetype": 2,
                        "words": [
                            "paper",
                            "rulers",
                            "pencils"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 83,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 5,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/5.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 707,
                            "origin": "https://oss.58haha.com/temp/5.png",
                            "tiny": "https://oss.58haha.com/temp/5.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1490180170,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 1,
                        "illustrator": "",
                        "introduction": "介绍孩子常见的工程机械类工具，激发学生对建造的兴趣。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 2581257,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "机械",
                            "工程建设"
                        ],
                        "themeinfos": null,
                        "title": "Machines That Work",
                        "top": 235,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419844,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 7,
                        "voicetype": 2,
                        "words": [
                            "tractor",
                            "bulldozer",
                            "crane"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 70,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 6,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/6.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/6.png",
                            "tiny": "https://oss.58haha.com/temp/6.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488456877,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过展示真实的自行车图片，认识自行车的各个部位。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 1612430,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "交通工具",
                            "部位"
                        ],
                        "themeinfos": null,
                        "title": "Bicycle Parts",
                        "top": 0,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419850,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 12,
                        "voicetype": 2,
                        "words": [
                            "bell",
                            "parts",
                            "seat"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 85,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 7,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/7.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/7.png",
                            "tiny": "https://oss.58haha.com/temp/7.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488457622,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过展示圣诞节相关的物品，帮助学生理解十二月和圣诞节的关系。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 2360662,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "时间",
                            "月份",
                            "节日"
                        ],
                        "themeinfos": null,
                        "title": "December",
                        "top": 0,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419849,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 10,
                        "voicetype": 2,
                        "words": [
                            "bells",
                            "cookies",
                            "stars"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 82,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 8,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/8.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/8.png",
                            "tiny": "https://oss.58haha.com/temp/9.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1512474124,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "介绍不同的国家和国旗，加深学生对国家的认知。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 1422425,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "国家",
                            "国旗"
                        ],
                        "themeinfos": null,
                        "title": "National Flags",
                        "top": 0,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419847,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 15,
                        "voicetype": 2,
                        "words": [
                            "China",
                            "Canada",
                            "Germany"
                        ],
                        "writer": ""
                    }
                ],
                "more": false,
                "offset": 14
            },
            "ext": {
                "difficultyinfos": [
                    {
                        "difficulty": 1,
                        "name": "A",
                        "level": 1,
                        "color": "#e36497",
                        "status": 0,
                        "count": 109,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 2,
                        "name": "B",
                        "level": 1,
                        "color": "#e8528e",
                        "status": 0,
                        "count": 112,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 3,
                        "name": "C",
                        "level": 1,
                        "color": "#ee4a74",
                        "status": 0,
                        "count": 239,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 4,
                        "name": "D",
                        "level": 2,
                        "color": "#e35050",
                        "status": 0,
                        "count": 228,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 5,
                        "name": "E",
                        "level": 2,
                        "color": "#ee6646",
                        "status": 0,
                        "count": 168,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 6,
                        "name": "F",
                        "level": 2,
                        "color": "#f37852",
                        "status": 0,
                        "count": 214,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 7,
                        "name": "G",
                        "level": 3,
                        "color": "#ff8a4a",
                        "status": 0,
                        "count": 203,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 8,
                        "name": "H",
                        "level": 3,
                        "color": "#ff9c00",
                        "status": 0,
                        "count": 150,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 9,
                        "name": "I",
                        "level": 3,
                        "color": "#fabb13",
                        "status": 0,
                        "count": 180,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 10,
                        "name": "J",
                        "level": 3,
                        "color": "#eede30",
                        "status": 0,
                        "count": 144,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 11,
                        "name": "K",
                        "level": 4,
                        "color": "#bdd94d",
                        "status": 0,
                        "count": 119,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 12,
                        "name": "L",
                        "level": 4,
                        "color": "#84cc60",
                        "status": 0,
                        "count": 96,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 13,
                        "name": "M",
                        "level": 4,
                        "color": "#4ed38d",
                        "status": 0,
                        "count": 112,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 14,
                        "name": "N",
                        "level": 4,
                        "color": "#25d3c9",
                        "status": 0,
                        "count": 83,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 15,
                        "name": "O",
                        "level": 5,
                        "color": "#06ceec",
                        "status": 0,
                        "count": 94,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 16,
                        "name": "P",
                        "level": 5,
                        "color": "#00cafd",
                        "status": 0,
                        "count": 54,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 17,
                        "name": "Q",
                        "level": 5,
                        "color": "#0192e5",
                        "status": 0,
                        "count": 46,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 18,
                        "name": "R",
                        "level": 5,
                        "color": "#2378e1",
                        "status": 0,
                        "count": 66,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 19,
                        "name": "S",
                        "level": 6,
                        "color": "#2e67ea",
                        "status": 0,
                        "count": 62,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 20,
                        "name": "T",
                        "level": 6,
                        "color": "#4261e2",
                        "status": 0,
                        "count": 50,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 21,
                        "name": "U",
                        "level": 6,
                        "color": "#7062dc",
                        "status": 0,
                        "count": 37,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 22,
                        "name": "V",
                        "level": 6,
                        "color": "#8e5de1",
                        "status": 0,
                        "count": 42,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 23,
                        "name": "W",
                        "level": 7,
                        "color": "#ac4fe1",
                        "status": 0,
                        "count": 35,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 24,
                        "name": "X",
                        "level": 7,
                        "color": "#c75ae2",
                        "status": 0,
                        "count": 47,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 25,
                        "name": "Y",
                        "level": 7,
                        "color": "#df64e3",
                        "status": 0,
                        "count": 64,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 26,
                        "name": "Z",
                        "level": 7,
                        "color": "#f26ec5",
                        "status": 0,
                        "count": 112,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    }
                ],
                "guidetext": "这是由英语教育专家精心安排的分级阅读学习体系，包含26个级别、1300多本牛津阅读树、大猫分级等原版英文读物，帮助小朋友系统化学习英文、阅读34232词汇量。",
                "isshowexplain": true,
                "levelinfo": {
                    "level": 0,
                    "count": 0,
                    "name": ""
                },
                "pkroute": "/offline_web?file=%2Fgame%2Findex.html%3Fbg_color%3D%231B96DC%26palfish_fullscreen%3D1%26level%3D1",
                "publishids": null,
                "readids": null,
                "totalbookcn": 2866,
                "userdifficultyinfo": {
                    "uid": 0,
                    "difficulty": 0,
                    "readcount": 0,
                    "publishcount": 0
                }
            }
}`
	var listR AutoGeneratedEList
	byteSlice := []byte(list)
	if err := json.Unmarshal(byteSlice, &listR); err != nil {

	}
	return listR
}

func ApiEnglishBookList1(c *gin.Context) {
	common.ReturnResponse(global.SUCCESS, map[string]interface{}{
		"data": listJson(),
	}, global.SUCCESS_MSG, c)
}

func ApiEnglishBookInfo1(c *gin.Context) {

	common.ReturnResponse(global.SUCCESS, map[string]interface{}{
		"info": "",
	}, global.SUCCESS_MSG, c)
}
