package app

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"wechat/common"
	"wechat/global"
)

type AutoGeneratedEList struct {
	Ent struct {
		Items  []interface{} `json:"items"`
		More   bool          `json:"more"`
		Offset int           `json:"offset"`
	} `json:"ent"`
	Ext struct {
		Difficultyinfos []struct {
			Difficulty int    `json:"difficulty"`
			Name       string `json:"name"`
			Level      int    `json:"level"`
			Color      string `json:"color"`
			Status     int    `json:"status"`
			Count      int    `json:"count"`
			Bgimg      string `json:"bgimg"`
		} `json:"difficultyinfos"`
		Guidetext     string `json:"guidetext"`
		Isshowexplain bool   `json:"isshowexplain"`
		Levelinfo     struct {
			Level int    `json:"level"`
			Count int    `json:"count"`
			Name  string `json:"name"`
		} `json:"levelinfo"`
		Pkroute            string      `json:"pkroute"`
		Publishids         interface{} `json:"publishids"`
		Readids            interface{} `json:"readids"`
		Totalbookcn        int         `json:"totalbookcn"`
		Userdifficultyinfo struct {
			UID          int `json:"uid"`
			Difficulty   int `json:"difficulty"`
			Readcount    int `json:"readcount"`
			Publishcount int `json:"publishcount"`
		} `json:"userdifficultyinfo"`
	} `json:"ext"`
}

func listJson() AutoGeneratedEList {
	list := `{
            "ent": {
                "items": [
                    {
                        "avescore": 93,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 1,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/1.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/1.png",
                            "tiny": "https://oss.58haha.com/temp/1.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1589173525,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过小猫玩耍的故事，介绍字母组合at的发音。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 1,
                        "playcount": 2166890,
                        "pressid": 1004,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "自然拼读",
                            "字母组合",
                            "动物"
                        ],
                        "themeinfos": null,
                        "title": "Cat",
                        "top": 1589434362,
                        "topicbookindex": 0,
                        "topicid": 276975692752910,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1630583891,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 9,
                        "voicetype": 2,
                        "words": [
                            "cat",
                            "hat",
                            "mat"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 85,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 2,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/2.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 704,
                            "origin": "https://oss.58haha.com/temp/2.png",
                            "tiny": "https://oss.58haha.com/temp/2.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1527578476,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过展示不同自然现象，帮助学生了解常见天气。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 14687033,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "天气",
                            "自然"
                        ],
                        "themeinfos": null,
                        "title": "Weather",
                        "top": 1531973280,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419846,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 6,
                        "voicetype": 2,
                        "words": [
                            "snowy",
                            "cloudy",
                            "rainy"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 87,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 3,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/3.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/3.png",
                            "tiny": "https://oss.58haha.com/temp/3.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488454921,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过不同小朋友手的照片，学习与手相关的各个部位的表达。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 3182006,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "身体部位",
                            "手"
                        ],
                        "themeinfos": null,
                        "title": "Hands",
                        "top": 1509035052,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419847,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 9,
                        "voicetype": 2,
                        "words": [
                            "hands",
                            "fingers",
                            "nails"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 90,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 4,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/4.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 704,
                            "origin": "https://oss.58haha.com/temp/4.png",
                            "tiny": "https://oss.58haha.com/temp/4.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488457018,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过介绍常见的不同学习用品，帮助孩子了解常见学习用品的名称。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 2729942,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "学校",
                            "学习用品"
                        ],
                        "themeinfos": null,
                        "title": "School Tools",
                        "top": 364,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419846,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 10,
                        "voicetype": 2,
                        "words": [
                            "paper",
                            "rulers",
                            "pencils"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 83,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 5,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/5.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 707,
                            "origin": "https://oss.58haha.com/temp/5.png",
                            "tiny": "https://oss.58haha.com/temp/5.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1490180170,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 1,
                        "illustrator": "",
                        "introduction": "介绍孩子常见的工程机械类工具，激发学生对建造的兴趣。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 2581257,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "机械",
                            "工程建设"
                        ],
                        "themeinfos": null,
                        "title": "Machines That Work",
                        "top": 235,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419844,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 7,
                        "voicetype": 2,
                        "words": [
                            "tractor",
                            "bulldozer",
                            "crane"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 70,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 6,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/6.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/6.png",
                            "tiny": "https://oss.58haha.com/temp/6.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488456877,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过展示真实的自行车图片，认识自行车的各个部位。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 1612430,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "交通工具",
                            "部位"
                        ],
                        "themeinfos": null,
                        "title": "Bicycle Parts",
                        "top": 0,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419850,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 12,
                        "voicetype": 2,
                        "words": [
                            "bell",
                            "parts",
                            "seat"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 85,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 7,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/7.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/7.png",
                            "tiny": "https://oss.58haha.com/temp/7.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1488457622,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "通过展示圣诞节相关的物品，帮助学生理解十二月和圣诞节的关系。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 2360662,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "时间",
                            "月份",
                            "节日"
                        ],
                        "themeinfos": null,
                        "title": "December",
                        "top": 0,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419849,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 10,
                        "voicetype": 2,
                        "words": [
                            "bells",
                            "cookies",
                            "stars"
                        ],
                        "writer": ""
                    },
                    {
                        "avescore": 82,
                        "bg_picture": "",
                        "bgm": "",
                        "bookid": 8,
                        "bookprice": "",
                        "booktype": 0,
                        "commoninfo": {
                            "bgimg": "https://oss.58haha.com/temp/8.png",
                            "color": "#e36497",
                            "count": 109,
                            "difficulty": 1,
                            "level": 1,
                            "name": "A",
                            "status": 0
                        },
                        "cover": {
                            "h": 706,
                            "origin": "https://oss.58haha.com/temp/8.png",
                            "tiny": "https://oss.58haha.com/temp/9.png",
                            "w": 600
                        },
                        "createrid": 0,
                        "ct": 1512474124,
                        "difficulty": 1,
                        "difficultyname": "A",
                        "domain": "",
                        "downloads": 0,
                        "explainvideo": "",
                        "explainvideostate": 0,
                        "firstclassifyid": 0,
                        "flag": 0,
                        "illustrator": "",
                        "introduction": "介绍不同的国家和国旗，加深学生对国家的认知。",
                        "isstoproll": false,
                        "isvip": false,
                        "lastupdateid": 0,
                        "learnlink": null,
                        "level": 1,
                        "levellist": null,
                        "listenvideo": "",
                        "listenvideostate": 0,
                        "lock": 0,
                        "newbubble": false,
                        "notinpicgallery": false,
                        "onlinetime": 0,
                        "pagecount": 0,
                        "paytype": 0,
                        "playcount": 1422425,
                        "pressid": 0,
                        "readbubble": false,
                        "recordbubble": false,
                        "recordstate": 20,
                        "reprice": 0,
                        "resid": 0,
                        "score": 1,
                        "screen": 0,
                        "secondclassifyid": 0,
                        "sort": 0,
                        "state": 2,
                        "tags": [
                            "国家",
                            "国旗"
                        ],
                        "themeinfos": null,
                        "title": "National Flags",
                        "top": 0,
                        "topicbookindex": 0,
                        "topicid": 0,
                        "topicstate": 1,
                        "translator": "",
                        "ut": 1627419847,
                        "version": 1,
                        "vipbubble": false,
                        "vocabulary": 15,
                        "voicetype": 2,
                        "words": [
                            "China",
                            "Canada",
                            "Germany"
                        ],
                        "writer": ""
                    }
                ],
                "more": false,
                "offset": 14
            },
            "ext": {
                "difficultyinfos": [
                    {
                        "difficulty": 1,
                        "name": "A",
                        "level": 1,
                        "color": "#e36497",
                        "status": 0,
                        "count": 109,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 2,
                        "name": "B",
                        "level": 1,
                        "color": "#e8528e",
                        "status": 0,
                        "count": 112,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 3,
                        "name": "C",
                        "level": 1,
                        "color": "#ee4a74",
                        "status": 0,
                        "count": 239,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 4,
                        "name": "D",
                        "level": 2,
                        "color": "#e35050",
                        "status": 0,
                        "count": 228,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/2b/e6/133a01bc6b4859c3f13a2727aaa0"
                    },
                    {
                        "difficulty": 5,
                        "name": "E",
                        "level": 2,
                        "color": "#ee6646",
                        "status": 0,
                        "count": 168,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 6,
                        "name": "F",
                        "level": 2,
                        "color": "#f37852",
                        "status": 0,
                        "count": 214,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 7,
                        "name": "G",
                        "level": 3,
                        "color": "#ff8a4a",
                        "status": 0,
                        "count": 203,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 8,
                        "name": "H",
                        "level": 3,
                        "color": "#ff9c00",
                        "status": 0,
                        "count": 150,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 9,
                        "name": "I",
                        "level": 3,
                        "color": "#fabb13",
                        "status": 0,
                        "count": 180,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/f5/15/cd656d52b12592d1d292c13f1011"
                    },
                    {
                        "difficulty": 10,
                        "name": "J",
                        "level": 3,
                        "color": "#eede30",
                        "status": 0,
                        "count": 144,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 11,
                        "name": "K",
                        "level": 4,
                        "color": "#bdd94d",
                        "status": 0,
                        "count": 119,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 12,
                        "name": "L",
                        "level": 4,
                        "color": "#84cc60",
                        "status": 0,
                        "count": 96,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 13,
                        "name": "M",
                        "level": 4,
                        "color": "#4ed38d",
                        "status": 0,
                        "count": 112,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 14,
                        "name": "N",
                        "level": 4,
                        "color": "#25d3c9",
                        "status": 0,
                        "count": 83,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/e4/de/3f2b9db8d0dd1dc65552f76c32a8"
                    },
                    {
                        "difficulty": 15,
                        "name": "O",
                        "level": 5,
                        "color": "#06ceec",
                        "status": 0,
                        "count": 94,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 16,
                        "name": "P",
                        "level": 5,
                        "color": "#00cafd",
                        "status": 0,
                        "count": 54,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 17,
                        "name": "Q",
                        "level": 5,
                        "color": "#0192e5",
                        "status": 0,
                        "count": 46,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 18,
                        "name": "R",
                        "level": 5,
                        "color": "#2378e1",
                        "status": 0,
                        "count": 66,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 19,
                        "name": "S",
                        "level": 6,
                        "color": "#2e67ea",
                        "status": 0,
                        "count": 62,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 20,
                        "name": "T",
                        "level": 6,
                        "color": "#4261e2",
                        "status": 0,
                        "count": 50,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 21,
                        "name": "U",
                        "level": 6,
                        "color": "#7062dc",
                        "status": 0,
                        "count": 37,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/dd/be/135a2801aa2a94702094444557b5"
                    },
                    {
                        "difficulty": 22,
                        "name": "V",
                        "level": 6,
                        "color": "#8e5de1",
                        "status": 0,
                        "count": 42,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 23,
                        "name": "W",
                        "level": 7,
                        "color": "#ac4fe1",
                        "status": 0,
                        "count": 35,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 24,
                        "name": "X",
                        "level": 7,
                        "color": "#c75ae2",
                        "status": 0,
                        "count": 47,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 25,
                        "name": "Y",
                        "level": 7,
                        "color": "#df64e3",
                        "status": 0,
                        "count": 64,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    },
                    {
                        "difficulty": 26,
                        "name": "Z",
                        "level": 7,
                        "color": "#f26ec5",
                        "status": 0,
                        "count": 112,
                        "bgimg": "https://qnyb17.cdn.ipalfish.com/17/picturebook/67/da/c52e43dca16dec8881aab41ee79b"
                    }
                ],
                "guidetext": "这是由英语教育专家精心安排的分级阅读学习体系，包含26个级别、1300多本牛津阅读树、大猫分级等原版英文读物，帮助小朋友系统化学习英文、阅读34232词汇量。",
                "isshowexplain": true,
                "levelinfo": {
                    "level": 0,
                    "count": 0,
                    "name": ""
                },
                "pkroute": "/offline_web?file=%2Fgame%2Findex.html%3Fbg_color%3D%231B96DC%26palfish_fullscreen%3D1%26level%3D1",
                "publishids": null,
                "readids": null,
                "totalbookcn": 2866,
                "userdifficultyinfo": {
                    "uid": 0,
                    "difficulty": 0,
                    "readcount": 0,
                    "publishcount": 0
                }
            }
}`
	var listR AutoGeneratedEList
	byteSlice := []byte(list)
	if err := json.Unmarshal(byteSlice, &listR); err != nil {

	}
	return listR
}

func ApiEnglishBookList1(c *gin.Context) {
	common.ReturnResponse(global.SUCCESS, map[string]interface{}{
		"data": listJson(),
	}, global.SUCCESS_MSG, c)
}

type AutoGeneInfo struct {
	Ent struct {
		Items []struct {
			Bookid  int64 `json:"bookid"`
			Pageid  int64 `json:"pageid"`
			Index   int   `json:"index"`
			Picture struct {
				Tiny   string `json:"tiny"`
				Origin string `json:"origin"`
				W      int    `json:"w"`
				H      int    `json:"h"`
			} `json:"picture"`
			Ct               int         `json:"ct"`
			Ut               int         `json:"ut"`
			State            int         `json:"state"`
			Text             string      `json:"text"`
			Picturev2        interface{} `json:"picturev2"`
			Flag             int         `json:"flag"`
			Topicstate       int         `json:"topicstate"`
			Ext              string      `json:"ext"`
			Recordtext       string      `json:"recordtext"`
			Translation      string      `json:"translation"`
			Hasteach         bool        `json:"hasteach"`
			Hasrecord        bool        `json:"hasrecord"`
			TextPinyin       string      `json:"textPinyin"`
			RecordtextPinyin string      `json:"recordtextPinyin"`
			IsOpenLp         bool        `json:"is_open_lp"`
			IsOpenRp         bool        `json:"is_open_rp"`
			BgPicture        string      `json:"bg_picture"`
			Scoretext        string      `json:"scoretext"`
		} `json:"items"`
		Offset         int  `json:"offset"`
		More           bool `json:"more"`
		Readpagecn     int  `json:"readpagecn"`
		Isshowvipguide bool `json:"isshowvipguide"`
	} `json:"ent"`
	Ext struct {
		Adpic    string `json:"adpic"`
		Adrouter string `json:"adrouter"`
		Bookinfo struct {
			Bookid int64  `json:"bookid"`
			Level  int    `json:"level"`
			Title  string `json:"title"`
			Cover  struct {
				Tiny   string `json:"tiny"`
				Origin string `json:"origin"`
				W      int    `json:"w"`
				H      int    `json:"h"`
			} `json:"cover"`
			Ct                int         `json:"ct"`
			Ut                int         `json:"ut"`
			State             int         `json:"state"`
			Domain            string      `json:"domain"`
			Downloads         int         `json:"downloads"`
			Resid             int         `json:"resid"`
			Screen            int         `json:"screen"`
			Top               int         `json:"top"`
			Flag              int         `json:"flag"`
			Playcount         int         `json:"playcount"`
			Pagecount         int         `json:"pagecount"`
			Score             int         `json:"score"`
			Version           int         `json:"version"`
			Lock              int         `json:"lock"`
			Recordstate       int         `json:"recordstate"`
			Topicstate        int         `json:"topicstate"`
			Vocabulary        int         `json:"vocabulary"`
			Difficulty        int         `json:"difficulty"`
			Isvip             bool        `json:"isvip"`
			Isstoproll        bool        `json:"isstoproll"`
			Topicid           int64       `json:"topicid"`
			Topicbookindex    int         `json:"topicbookindex"`
			Vipbubble         bool        `json:"vipbubble"`
			Newbubble         bool        `json:"newbubble"`
			Recordbubble      bool        `json:"recordbubble"`
			Onlinetime        int         `json:"onlinetime"`
			Readbubble        bool        `json:"readbubble"`
			Themeinfos        interface{} `json:"themeinfos"`
			Notinpicgallery   bool        `json:"notinpicgallery"`
			Tags              []string    `json:"tags"`
			Words             []string    `json:"words"`
			Introduction      string      `json:"introduction"`
			Voicetype         int         `json:"voicetype"`
			Pressid           int         `json:"pressid"`
			Booktype          int         `json:"booktype"`
			Illustrator       string      `json:"illustrator"`
			Translator        string      `json:"translator"`
			Writer            string      `json:"writer"`
			Bgm               string      `json:"bgm"`
			Firstclassifyid   int         `json:"firstclassifyid"`
			Secondclassifyid  int         `json:"secondclassifyid"`
			Paytype           int         `json:"paytype"`
			Sort              int         `json:"sort"`
			Levellist         interface{} `json:"levellist"`
			Createrid         int         `json:"createrid"`
			Lastupdateid      int         `json:"lastupdateid"`
			Avescore          int         `json:"avescore"`
			Learnlink         []int       `json:"learnlink"`
			Reprice           int         `json:"reprice"`
			Bookprice         string      `json:"bookprice"`
			Difficultyname    string      `json:"difficultyname"`
			Explainvideo      string      `json:"explainvideo"`
			Listenvideo       string      `json:"listenvideo"`
			Explainvideostate int         `json:"explainvideostate"`
			Listenvideostate  int         `json:"listenvideostate"`
			BgPicture         string      `json:"bg_picture"`
		} `json:"bookinfo"`
		Cwrouter    string `json:"cwrouter"`
		Endtext     string `json:"endtext"`
		Evaluations []struct {
			Recordid   int64 `json:"recordid"`
			Totalscore struct {
				Content string `json:"content"`
				Score   int    `json:"score"`
				Rank    int    `json:"rank"`
				Index   int    `json:"index"`
				Startts int    `json:"startts"`
				Endts   int    `json:"endts"`
			} `json:"totalscore"`
			Wordscore []struct {
				Content string `json:"content"`
				Score   int    `json:"score"`
				Rank    int    `json:"rank"`
				Index   int    `json:"index"`
				Startts int    `json:"startts"`
				Endts   int    `json:"endts"`
			} `json:"wordscore"`
			Productid int64 `json:"productid"`
			Ut        int   `json:"ut"`
		} `json:"evaluations"`
		Isconfirm      bool `json:"isconfirm"`
		Isshowvipguide bool `json:"isshowvipguide"`
		Productinfo    struct {
			Productid   int64 `json:"productid"`
			Bookid      int64 `json:"bookid"`
			UID         int   `json:"uid"`
			State       int   `json:"state"`
			Ct          int   `json:"ct"`
			Ut          int   `json:"ut"`
			Playcount   int   `json:"playcount"`
			Likecount   int   `json:"likecount"`
			Islike      bool  `json:"islike"`
			Publishtime int   `json:"publishtime"`
			Producttype int   `json:"producttype"`
			Score       int   `json:"score"`
			Rank        int   `json:"rank"`
			Iscollect   bool  `json:"iscollect"`
			Dt          int   `json:"dt"`
			Scene       int   `json:"scene"`
		} `json:"productinfo"`
		Readpagecn int `json:"readpagecn"`
		Records    []struct {
			Recordid  int64  `json:"recordid"`
			Productid int64  `json:"productid"`
			URL       string `json:"url"`
			Ct        int    `json:"ct"`
			Ut        int    `json:"ut"`
			Pageid    int64  `json:"pageid"`
			Duration  int    `json:"duration"`
			Bookid    int64  `json:"bookid"`
			Rawurl    string `json:"rawurl"`
		} `json:"records"`
		Route        string `json:"route"`
		Sharecontent string `json:"sharecontent"`
		Users        []struct {
			ID          int    `json:"id"`
			Name        string `json:"name"`
			Avatar      string `json:"avatar"`
			Gender      int    `json:"gender"`
			Sign        string `json:"sign"`
			Regtype     int    `json:"regtype"`
			Cate        int    `json:"cate"`
			Birthday    int    `json:"birthday"`
			Origavatar  string `json:"origavatar"`
			Audiobrief  string `json:"audiobrief"`
			Audiolength int    `json:"audiolength"`
			Ct          int    `json:"ct"`
			Rt          int    `json:"rt"`
			Country     string `json:"country"`
			Govold      int    `json:"govold"`
			Rmk         string `json:"rmk"`
			Gov         int    `json:"gov"`
			Title       string `json:"title"`
			Source      int    `json:"source"`
			Juniortitle string `json:"juniortitle"`
			Enname      string `json:"enname"`
			Iseligible  bool   `json:"iseligible"`
			State       int    `json:"state"`
			Fullname    struct {
				Firstname  string `json:"firstname"`
				Familyname string `json:"familyname"`
				Middlename string `json:"middlename"`
				Status     int    `json:"status"`
			} `json:"fullname"`
			Puid     string `json:"puid"`
			Agelevel string `json:"agelevel"`
		} `json:"users"`
	} `json:"ext"`
}

func infoJson() AutoGeneInfo {
	info := `{
            "ent": {
                "items": [
                    {
                        "bookid": 1,
                        "pageid": 357116961990692,
                        "index": 2,
                        "picture": {
                            "tiny": "https://oss.58haha.com/temp/ext/4.png",
                            "origin": "https://oss.58haha.com/temp/ext/4.png",
                            "w": 720,
                            "h": 720
                        },
                        "ct": 1589173516,
                        "ut": 1618803706,
                        "state": 0,
                        "text": "Cat",
                        "picturev2": null,
                        "flag": 0,
                        "topicstate": 0,
                        "ext": "",
                        "recordtext": "",
                        "translation": "",
                        "hasteach": false,
                        "hasrecord": false,
                        "textPinyin": "",
                        "recordtextPinyin": "",
                        "is_open_lp": false,
                        "is_open_rp": false,
                        "bg_picture": "",
                        "scoretext": ""
                    }
                ],
                "offset": 7,
                "more": false,
                "readpagecn": 3,
                "isshowvipguide": true
            },
            "ext": {
                "adpic": "http://qnyb00.cdn.ipalfish.com/0/img/b4/75/68b84cf742fe8bd0419bc13f2323",
                "adrouter": "/utils/commondialog?dialogbg=http%3A%2F%2Fqnyb00.cdn.ipalfish.com%2F0%2Fimg%2F93%2F75%2Fb53424bcc26136314b94ddd8c855&content=%3Cfont%20color%3D%22%23ff6600%22%3E%E5%8D%87%E7%BA%A7VIP%EF%BC%8C%E4%BA%AB%E7%BB%98%E6%9C%AC%E7%82%B9%E8%AF%BB%E7%89%B9%E6%9D%83%3C%2Ffont%3E%3Cbr%3E%E8%BF%98%E6%9C%8911%E9%A1%B9%E7%89%B9%E6%9D%83%E7%AD%89%E4%BD%A0%E9%A2%86%E5%8F%96&rightbtnstr=%E7%AB%8B%E5%8D%B3%E5%8D%87%E7%BA%A7VIP&router=%2Fweb%3Furl%3Dhttps%253A%252F%252Fwww.ipalfish.com%252Fpicturebook%252Fpay%252Fzhongshen.html%253Fchannel%253D659%2526needblurbackground%253D0",
                "bookinfo": {
                    "bookid": 357116938620964,
                    "level": 1,
                    "title": "Cat",
                    "cover": {
                        "tiny": "https://qnyb17.cdn.ipalfish.com/17/picturebook/7e/23/30cedc641d5757d5e21663d56dba",
                        "origin": "https://qnyb17.cdn.ipalfish.com/17/picturebook/3c/0e/11d658d115f0ce4d48a9a4e63d48",
                        "w": 600,
                        "h": 706
                    },
                    "ct": 1589173525,
                    "ut": 1630583891,
                    "state": 2,
                    "domain": "",
                    "downloads": 0,
                    "resid": 0,
                    "screen": 0,
                    "top": 1589434362,
                    "flag": 0,
                    "playcount": 2166915,
                    "pagecount": 0,
                    "score": 1,
                    "version": 1,
                    "lock": 0,
                    "recordstate": 20,
                    "topicstate": 1,
                    "vocabulary": 9,
                    "difficulty": 1,
                    "isvip": false,
                    "isstoproll": false,
                    "topicid": 276975692752910,
                    "topicbookindex": 0,
                    "vipbubble": false,
                    "newbubble": false,
                    "recordbubble": false,
                    "onlinetime": 0,
                    "readbubble": false,
                    "themeinfos": null,
                    "notinpicgallery": false,
                    "tags": [
                        "自然拼读",
                        "字母组合",
                        "动物"
                    ],
                    "words": [
                        "cat",
                        "hat",
                        "mat"
                    ],
                    "introduction": "通过小猫玩耍的故事，介绍字母组合at的发音。",
                    "voicetype": 2,
                    "pressid": 1004,
                    "booktype": 0,
                    "illustrator": "",
                    "translator": "",
                    "writer": "",
                    "bgm": "",
                    "firstclassifyid": 0,
                    "secondclassifyid": 0,
                    "paytype": 1,
                    "sort": 0,
                    "levellist": null,
                    "createrid": 0,
                    "lastupdateid": 0,
                    "avescore": 93,
                    "learnlink": [
                        1,
                        2,
                        3
                    ],
                    "reprice": 0,
                    "bookprice": "",
                    "difficultyname": "A",
                    "explainvideo": "",
                    "listenvideo": "",
                    "explainvideostate": 0,
                    "listenvideostate": 0,
                    "bg_picture": ""
                },
                "cwrouter": "/picturebook/click_read/357116938620964?url=palfishoffline%3a%2f%2fmwt%2fmwt%2findex.html",
                "endtext": "别走开，马上进入读绘本环节",
                "evaluations": [
                    {
                        "recordid": 357650427342884,
                        "totalscore": {
                            "content": "Cat",
                            "score": 100,
                            "rank": 3,
                            "index": 0,
                            "startts": 0,
                            "endts": 0
                        },
                        "wordscore": [
                            {
                                "content": "Cat",
                                "score": 96,
                                "rank": 3,
                                "index": 0,
                                "startts": 36,
                                "endts": 102
                            }
                        ],
                        "productid": 357650343829535,
                        "ut": 1596534671
                    },
                    {
                        "recordid": 357650446882852,
                        "totalscore": {
                            "content": "Cat.",
                            "score": 100,
                            "rank": 3,
                            "index": 0,
                            "startts": 0,
                            "endts": 0
                        },
                        "wordscore": [
                            {
                                "content": "Cat",
                                "score": 96,
                                "rank": 3,
                                "index": 0,
                                "startts": 33,
                                "endts": 99
                            }
                        ],
                        "productid": 357650343829535,
                        "ut": 1596534671
                    },
                    {
                        "recordid": 357650467921956,
                        "totalscore": {
                            "content": "Hat.",
                            "score": 100,
                            "rank": 3,
                            "index": 0,
                            "startts": 0,
                            "endts": 0
                        },
                        "wordscore": [
                            {
                                "content": "Hat",
                                "score": 96,
                                "rank": 3,
                                "index": 0,
                                "startts": 24,
                                "endts": 102
                            }
                        ],
                        "productid": 357650343829535,
                        "ut": 1596534671
                    },
                    {
                        "recordid": 357650500100132,
                        "totalscore": {
                            "content": "Cat sat.",
                            "score": 100,
                            "rank": 3,
                            "index": 0,
                            "startts": 0,
                            "endts": 0
                        },
                        "wordscore": [
                            {
                                "content": "Cat",
                                "score": 95,
                                "rank": 3,
                                "index": 0,
                                "startts": 51,
                                "endts": 108
                            },
                            {
                                "content": "sat",
                                "score": 96,
                                "rank": 3,
                                "index": 1,
                                "startts": 114,
                                "endts": 183
                            }
                        ],
                        "productid": 357650343829535,
                        "ut": 1596534670
                    },
                    {
                        "recordid": 357650523557924,
                        "totalscore": {
                            "content": "Cat.",
                            "score": 100,
                            "rank": 3,
                            "index": 0,
                            "startts": 0,
                            "endts": 0
                        },
                        "wordscore": [
                            {
                                "content": "Cat",
                                "score": 95,
                                "rank": 3,
                                "index": 0,
                                "startts": 36,
                                "endts": 117
                            }
                        ],
                        "productid": 357650343829535,
                        "ut": 1596534670
                    },
                    {
                        "recordid": 357650544625700,
                        "totalscore": {
                            "content": "Mat.",
                            "score": 100,
                            "rank": 3,
                            "index": 0,
                            "startts": 0,
                            "endts": 0
                        },
                        "wordscore": [
                            {
                                "content": "Mat",
                                "score": 95,
                                "rank": 3,
                                "index": 0,
                                "startts": 30,
                                "endts": 99
                            }
                        ],
                        "productid": 357650343829535,
                        "ut": 1596534670
                    },
                    {
                        "recordid": 357650588168228,
                        "totalscore": {
                            "content": "Cat sat.",
                            "score": 100,
                            "rank": 3,
                            "index": 0,
                            "startts": 0,
                            "endts": 0
                        },
                        "wordscore": [
                            {
                                "content": "Cat",
                                "score": 96,
                                "rank": 3,
                                "index": 0,
                                "startts": 45,
                                "endts": 96
                            },
                            {
                                "content": "sat",
                                "score": 96,
                                "rank": 3,
                                "index": 1,
                                "startts": 99,
                                "endts": 171
                            }
                        ],
                        "productid": 357650343829535,
                        "ut": 1596534670
                    }
                ],
                "isconfirm": false,
                "isshowvipguide": false,
                "productinfo": {
                    "productid": 357650343829535,
                    "bookid": 357116938620964,
                    "uid": 602244,
                    "state": 0,
                    "ct": 1589433956,
                    "ut": 1719411146,
                    "playcount": 1487008,
                    "likecount": 43,
                    "islike": false,
                    "publishtime": 1589433956,
                    "producttype": 1,
                    "score": 0,
                    "rank": 0,
                    "iscollect": false,
                    "dt": 0,
                    "scene": 0
                },
                "readpagecn": -1,
                "records": [
                    {
                        "recordid": 357650427342884,
                        "productid": 357650343829535,
                        "url": "",
                        "ct": 1589433997,
                        "ut": 1589433997,
                        "pageid": 357116961990692,
                        "duration": 0,
                        "bookid": 357116938620964,
                        "rawurl": ""
                    }
                ],
                "route": "/web?url=https%3A%2F%2Fwww.ipalfish.com%2Fipalfish-gods-pen%2Fview%2F250026",
                "sharecontent": "【拜托帮我助力一下~我家宝贝想0元学VIP绘本！谢谢~】\nhttps://i2mi.com/MjE4YTA1\n复制整条信息，打开【伴鱼绘本】，帮我助力你家宝贝也能0元学~\n丨S6J3YFY1va丨",
                "users": [
                    {
                        "id": 602244,
                        "name": "绘本小鱼鱼仔",
                        "avatar": "https://qnyb00.cdn.ipalfish.com/0/img/c2/14/fe09cde968b2388d3817e39c4d2b",
                        "gender": 2,
                        "sign": "BARKING IN PALFISH",
                        "regtype": 1,
                        "cate": 1,
                        "birthday": 1451606400,
                        "origavatar": "https://qnyb00.cdn.ipalfish.com/0/img/01/99/82c7e1e003b15f44aa3ea01c3be8",
                        "audiobrief": "https://qnyb00.cdn.ipalfish.com/0/aud/b6/36/54e46230982002adce05c97595ab",
                        "audiolength": 1,
                        "ct": 1469018389,
                        "rt": 1469018484,
                        "country": "",
                        "govold": 0,
                        "rmk": "",
                        "gov": 0,
                        "title": "",
                        "source": 0,
                        "juniortitle": "",
                        "enname": "1234b",
                        "iseligible": false,
                        "state": 0,
                        "fullname": {
                            "firstname": "",
                            "familyname": "",
                            "middlename": "",
                            "status": 0
                        },
                        "puid": "376170167448",
                        "agelevel": ""
                    }
                ]
            }
}`
	var listR AutoGeneInfo
	byteSlice := []byte(info)
	if err := json.Unmarshal(byteSlice, &listR); err != nil {

	}
	return listR
}
func ApiEnglishBookInfo1(c *gin.Context) {

	common.ReturnResponse(global.SUCCESS, map[string]interface{}{
		"data": infoJson(),
	}, global.SUCCESS_MSG, c)
}
